version: '3.8'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: 'secure#123'
      MYSQL_ROOT_PASSWORD: 'secure#123'
      MYSQL_USER: 'user'
    ports:
      - '3306:3306'
