version: '3'
services:
  db:
    container_name: mpesa-integration
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'admin@Database'
      MYSQL_DATABASE: 'mpesa_integration'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'admin@Database'
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - '3308:3306'