app:
  integrations:
    mpesa:
      consumer-key: YOUR_ACCESS_KEY
      consumer-secret: YOUR_ACCESS_TOKEN
      domain: http://sandbox.safaricom.co.ke
      shortCode: MPESA_SHORT_CODE
      express:
        shortCode: MPESA_SHORT_CODE